#!/bin/sh
set -e

# If SECRET_ENCRYPTION_KEY not set, try reading from shared volume
# (auto-generated by the API container's entrypoint-bun.sh).
if [ -z "$SECRET_ENCRYPTION_KEY" ]; then
  SECRET_KEY_FILE="/app/data/secret-encryption-key"
  if [ -f "$SECRET_KEY_FILE" ] && [ -s "$SECRET_KEY_FILE" ]; then
    export SECRET_ENCRYPTION_KEY
    SECRET_ENCRYPTION_KEY=$(cat "$SECRET_KEY_FILE")
    echo "Loaded SECRET_ENCRYPTION_KEY from shared volume"
  else
    echo "WARNING: SECRET_ENCRYPTION_KEY not set and not found in $SECRET_KEY_FILE"
    echo "  The API container must start first to auto-generate the key."
  fi
fi

exec onecli-gateway "$@"
